# app/validators/rules.py
MIN_WALL_MM = 0.8
MIN_STRUCTURAL_THICKNESS_MM = 3.0
MAX_STRUCTURAL_THICKNESS_MM = 8.0
MIN_RAISED_TEXT_DEPTH_MM = 0.6
MAX_RAISED_TEXT_DEPTH_MM = 1.4
MIN_READABLE_TEXT_HEIGHT_MM = 6.0
MIN_HOLE_DIAMETER_MM = 4.5
MAX_HOLE_DIAMETER_MM = 8.0
MIN_EDGE_CLEARANCE_MM = 3.0
MIN_HANGER_WIDTH_MM = 45.0
MIN_HANGER_HEIGHT_MM = 30.0
MAX_HANGER_WIDTH_MM = 120.0
MAX_HANGER_HEIGHT_MM = 80.0
MAX_TEXT_CHARS_WITHOUT_WIDTH_GROWTH = 16
